# Generated by Django 5.2.8 on 2025-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
