# Generated by Django 5.2.8 on 2025-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
