# Generated by Django 5.2.8 on 2025-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prayer', '0002_pdf_order_pdf_updated_at_video_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
