# Generated by Django 5.2.8 on 2025-12-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doaa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doaa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doaa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
