# Generated by Django 5.2.8 on 2025-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doaa', '0002_doaa_created_at_doaa_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doaa',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
